import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Navbar";
import AuthProvider from "./auth/components/Provider";
import { getServerSession } from "next-auth";
import { authOption } from "./auth/components/AuthOption";
import dbConnect from "./mongodb/mongodb";
import SocketProvider from "./context/SocketProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get the user's session
  const session = await getServerSession(authOption);
  await dbConnect();
  return (
    <html lang="en">
      <AuthProvider>
        <SocketProvider>
          <body>
            {session?.user ? (
              <div className="flex items-center justify-center h-screen">
                <div className="grid grid-cols-12 gap-3 w-full h-full max-w-7xl">
                  <div className="col-span-1 h-full">
                    <Navbar />
                  </div>
                  <main className="col-span-11 overflow-y-auto">
                    {children}
                  </main>
                </div>
              </div>
            ) : (
              <main>{children}</main>
            )}
          </body>
        </SocketProvider>
      </AuthProvider>
    </html>
  );
}
