const MESSAGE_ALERT = "MESSAGE_ALERT";
const FRIEND_REQUEST = "FRIEND_REQUEST";
const USER_REGISTER = "USER_REGISTER";

const INCOMMING_MESSAGE = "INCOMMING_MESSAGE";
const INCOMMING_MESSAGE_ALERT = "INCOMMING_MESSAGE_ALERT";
const INCOMMING_MESSAGE_READ = "INCOMMING_MESSAGE_READ";
const MESSAGE_SAVED = "MESSAGE_SAVED";


export {
  MESSAGE_ALERT,
  FRIEND_REQUEST,
  USER_REGISTER,
  INCOMMING_MESSAGE,
  INCOMMING_MESSAGE_ALERT,
  INCOMMING_MESSAGE_READ,
  MESSAGE_SAVED
};
